/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examsystem;
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import java.awt.Color;
import java.sql.*;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.JOptionPane;
import javax.swing.ButtonGroup;
import javax.swing.JRadioButton;

/**
 *
 * @author HARSHIT
 */
 
public class MainTest extends javax.swing.JFrame {

    /**
     * Creates new form MainTest
     */
    
    int a=0,b=0,c=0,d=0,e=0;
    int l5=0;
    
     private java.sql.Connection con;
    private Statement stmt;
    private java.sql.PreparedStatement pst;
    private ResultSet rs;
    int b1=0;
    int b2=0;
    int b3=0;
    int b4=0;
    int b5=0;
    int counter =300;
    Boolean isIt = false;
  int question=0;
    int count=0;
    
    JRadioButton jb5=new JRadioButton();
     
    public MainTest() {
       
        initComponents();
        {   this.getContentPane().setBackground(Color.green);
        buttonGroup1.add(jRadioButton1);
        buttonGroup1.add(jRadioButton2);
        buttonGroup1.add(jRadioButton3);
        buttonGroup1.add(jRadioButton4);
        buttonGroup1.add(jb5);
        
            try{   
                 
      Class.forName("com.mysql.jdbc.Driver");
      con=DriverManager.getConnection("jdbc:mysql://localhost:3306/examsystem","root","");
      stmt=con.createStatement();
     
     }
     catch(Exception e){
         System.out.print("error"+e.getMessage());
     }}
        
        
        
    }
    public MainTest(String str){
            initComponents();
            
            
      
        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("START TEST");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 3, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 10)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("TIMER");

        jTextArea1.setBackground(new java.awt.Color(204, 204, 204));
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setEditable(false);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel3.setText("WELCOME TO THE TEST");

        jButton2.setText("NEXT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("FINISH TEST");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Verdana", 3, 14)); // NOI18N
        jButton4.setText("1");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Verdana", 3, 14)); // NOI18N
        jButton5.setText("2");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton9.setFont(new java.awt.Font("Verdana", 3, 14)); // NOI18N
        jButton9.setText("3");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setFont(new java.awt.Font("Verdana", 3, 14)); // NOI18N
        jButton10.setText("4");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setFont(new java.awt.Font("Verdana", 3, 14)); // NOI18N
        jButton11.setText("5");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Verdana", 3, 14)); // NOI18N
        jLabel6.setText("USERNAME");

        jLabel7.setFont(new java.awt.Font("Verdana", 3, 14)); // NOI18N
        jLabel7.setText("hkataria11");

        jLabel9.setFont(new java.awt.Font("Verdana", 3, 14)); // NOI18N
        jLabel9.setText("CORRECT ");

        jLabel11.setFont(new java.awt.Font("Verdana", 3, 14)); // NOI18N
        jLabel11.setText("PERCENTAGE");

        jLabel13.setFont(new java.awt.Font("Verdana", 3, 14)); // NOI18N
        jLabel13.setText("RESULT PAGE");

        jLabel14.setFont(new java.awt.Font("Verdana", 3, 14)); // NOI18N
        jLabel14.setText("TOTAL");

        jLabel16.setFont(new java.awt.Font("Verdana", 3, 14)); // NOI18N
        jLabel16.setText("5");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel11)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(29, 29, 29))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(42, 42, 42))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(69, 69, 69))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(122, 122, 122)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton7.setBackground(Color.RED);

        jLabel4.setFont(new java.awt.Font("Verdana", 3, 10)); // NOI18N
        jLabel4.setText(" NOT ATTEMPTED");

        jLabel18.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        jLabel18.setText("ATTEMPTED");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addComponent(jButton5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton11)
                        .addGap(39, 39, 39)))
                .addGap(55, 55, 55)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(34, 34, 34))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(59, 59, 59)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(56, 56, 56)
                        .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(76, 76, 76)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 442, Short.MAX_VALUE))
        );

        jLabel8.setFont(new java.awt.Font("Verdana", 2, 10)); // NOI18N
        jLabel8.setText("WHICH SUBJECT YOU WANT TO CHOOSE");

        jLabel17.setFont(new java.awt.Font("Verdana", 3, 14)); // NOI18N
        jLabel17.setText("WELCOME");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jRadioButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jRadioButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jRadioButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jRadioButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 713, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(350, 350, 350)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(89, 89, 89)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 713, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jButton1)
                        .addGap(74, 74, 74)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(104, 104, 104)
                        .addComponent(jButton3)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2)
                                .addComponent(jLabel17)))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton4)
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2)
                            .addComponent(jButton3))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
void setQues(){
    jb5.setSelected(true);
    if(question==0){
        try{   
             String s = jTextField1.getText();
            try{
                String sql="Select Ques0,Ques0Op0,Ques0Op2,Ques0Op3,Ques0Op4 FROM Ques WHERE Course='"+(s)+"'";
                rs=stmt.executeQuery(sql);
                String ques="";
                String op1="";
                String op2="";
                String op3="";
                String op4="";
                
                while(rs.next()){
                    ques= rs.getString("Ques0");
              op1=rs.getString("Ques0Op0");
             op2=rs.getString("Ques0Op2");
             op3=rs.getString("Ques0Op3");
             op4=rs.getString("Ques0Op4");
              stmt=con.createStatement();
                }  
                 
             jTextArea1.setText(ques);
              jRadioButton1.setText(op1);
             jRadioButton2.setText(op2);
             jRadioButton3.setText(op3);
             jRadioButton4.setText(op4);
             stmt=con.createStatement();
             
            }
                   
                
                
                
           
            
            catch (SQLException e ) {
    e.printStackTrace();

}
         
        
         }
         catch(Exception e){
             e.printStackTrace();
         }
    }
     if(question==1){
         try{   
             String s = jTextField1.getText();
            try{
                String sql3="select Course  from ques where Course='"+(s)+"'";
                rs=stmt.executeQuery(sql3);
                String course="";
                while(rs.next()){
                    course=rs.getString("Course");

                    stmt=con.createStatement();
                }
                String sql2="SELECT Course,Ques2,Ques2Op0,Ques2Op2,Ques2Op3,Ques2Op4 FROM ques WHERE Course='"+(s)+"'";
               rs=stmt.executeQuery(sql2);
                
                String ques="";
                String op1="";
                String op2="";
                String op3="";
                String op4="";
            while(rs.next()) { 
             ques= rs.getString("Ques2");
              op1=rs.getString("Ques2Op0");
             op2=rs.getString("Ques2Op2");
             op3=rs.getString("Ques2Op3");
             op4=rs.getString("Ques2Op4");
             stmt=con.createStatement();
            }
            if(s.equals(String.valueOf(course))){
             jTextArea1.setText(ques);
              jRadioButton1.setText(op1);
             jRadioButton2.setText(op2);
             jRadioButton3.setText(op3);
             jRadioButton4.setText(op4);
             stmt=con.createStatement();
             }
            }
            catch (SQLException e ) {
    e.printStackTrace();

}
         
        
         }
         catch(Exception e){
             e.printStackTrace();
         }
        }
     if(question==2){
         try{   
             String s = jTextField1.getText();
            try{
                String sql3="select Course  from ques where Course='"+(s)+"'";
                rs=stmt.executeQuery(sql3);
                String course="";
                while(rs.next()){
                    course=rs.getString("Course");

                    stmt=con.createStatement();
                }
                String sql2="SELECT Course,Ques3,Ques3Op0,Ques3Op2,Ques3Op3,Ques3Op4 FROM ques WHERE Course='"+(s)+"'";
               rs=stmt.executeQuery(sql2);
                
                String ques="";
                String op1="";
                String op2="";
                String op3="";
                String op4="";
            while(rs.next()) { 
             ques= rs.getString("Ques3");
              op1=rs.getString("Ques3Op0");
             op2=rs.getString("Ques3Op2");
             op3=rs.getString("Ques3Op3");
             op4=rs.getString("Ques3Op4");
             stmt=con.createStatement();
            }
            if(s.equals(String.valueOf(course))){
             jTextArea1.setText(ques);
              jRadioButton1.setText(op1);
             jRadioButton2.setText(op2);
             jRadioButton3.setText(op3);
             jRadioButton4.setText(op4);
             stmt=con.createStatement();
             }
            }
            catch (SQLException e ) {
    e.printStackTrace();

}
         
        
         }
         catch(Exception e){
             e.printStackTrace();
         }
    }
    
        if(question==3){
             try{   
             String s = jTextField1.getText();
            try{
                String sql3="select Course  from ques where Course='"+(s)+"'";
                rs=stmt.executeQuery(sql3);
                String course="";
                while(rs.next()){
                    course=rs.getString("Course");

                    stmt=con.createStatement();
                }
                String sql2="SELECT Course,Ques4,Ques4Op0,Ques4Op2,Ques4Op3,Ques4Op4 FROM ques WHERE Course='"+(s)+"'";
               rs=stmt.executeQuery(sql2);
                
                String ques="";
                String op1="";
                String op2="";
                String op3="";
                String op4="";
            while(rs.next()) { 
             ques= rs.getString("Ques4");
              op1=rs.getString("Ques4Op0");
             op2=rs.getString("Ques4Op2");
             op3=rs.getString("Ques4Op3");
             op4=rs.getString("Ques4Op4");
             stmt=con.createStatement();
            }
            if(s.equals(String.valueOf(course))){
             jTextArea1.setText(ques);
              jRadioButton1.setText(op1);
             jRadioButton2.setText(op2);
             jRadioButton3.setText(op3);
             jRadioButton4.setText(op4);
             stmt=con.createStatement();
             }
            }
            catch (SQLException e ) {
    e.printStackTrace();

}
         
        
         }
         catch(Exception e){
             e.printStackTrace();
         }
        }
    
            if(question==4){
                 try{   
             String s = jTextField1.getText();
            try{
                String sql3="select Course  from ques where Course='"+(s)+"'";
                rs=stmt.executeQuery(sql3);
                String course="";
                while(rs.next()){
                    course=rs.getString("Course");

                    stmt=con.createStatement();
                }
                String sql2="SELECT Course,Ques5,Ques5Op0,Ques5Op2,Ques5Op3,Ques5Op4 FROM ques WHERE Course='"+(s)+"'";
               rs=stmt.executeQuery(sql2);
                
                String ques="";
                String op1="";
                String op2="";
                String op3="";
                String op4="";
            while(rs.next()) { 
             ques= rs.getString("Ques5");
              op1=rs.getString("Ques5Op0");
             op2=rs.getString("Ques5Op2");
             op3=rs.getString("Ques5Op3");
             op4=rs.getString("Ques5Op4");
             stmt=con.createStatement();
            }
            if(s.equals(String.valueOf(course))){
             jTextArea1.setText(ques);
              jRadioButton1.setText(op1);
             jRadioButton2.setText(op2);
             jRadioButton3.setText(op3);
             jRadioButton4.setText(op4);
             stmt=con.createStatement();
             }
            }
            catch (SQLException e ) {
    e.printStackTrace();

}
         
        
         }
         catch(Exception e){
             e.printStackTrace();
         }
            }
}    

void check(){
    if(question==0){
        try{   
             String s = jTextField1.getText();
            try{
                String sql3="Select Course from ques where Course='"+(s)+"'";
                rs=stmt.executeQuery(sql3);
                String course="";
                while(rs.next()){
                    course=rs.getString("Course");

                    stmt=con.createStatement();
                }
                String sql2="SELECT Correct0 FROM ques WHERE Course='"+(s)+"'";
               rs=stmt.executeQuery(sql2);
            String correct1="";
            while(rs.next()){
                correct1=rs.getString("Correct0");
                stmt=con.createStatement();
              String crb1=jRadioButton1.getText();
              String crb2=jRadioButton2.getText();
              String crb3=jRadioButton3.getText();
              String crb4=jRadioButton4.getText();
              if(jRadioButton1.isSelected() && crb1.equals(correct1)){
                  count++;
                 
              }
              else
                  if(jRadioButton2.isSelected() && crb2.equals(correct1)){
                  count++;
            }
              else
                      if(jRadioButton3.isSelected() && crb3.equals(correct1)){
                  count++;
                
                      }
              else
                          if(jRadioButton4.isSelected() && crb4.equals(correct1)){
                  count++;
            }
              if(jRadioButton1.isSelected()||jRadioButton2.isSelected()||jRadioButton3.isSelected()||jRadioButton4.isSelected()){
           jButton4.setBackground(Color.RED);
                 
              }
              if(jRadioButton1.isSelected()){
                 a=1;
              }
              else
                  if(jRadioButton2.isSelected()){
                      a=2;
            }
              else
                      if(jRadioButton3.isSelected()){
                a=3;
                      }
              else
                          if(jRadioButton4.isSelected()){
                              a=4;
            }
              
            }
            }
            catch (SQLException e ) {
    e.printStackTrace();

}
         
        
         }
         catch(Exception e){
             e.printStackTrace();
         }
    }
    
     if(question==1){
         try{   
             String s = jTextField1.getText();
            try{
                String sql3="select Course from ques where Course='"+(s)+"'";
                rs=stmt.executeQuery(sql3);
                String course="";
                while(rs.next()){
                    course=rs.getString("Course");

                    stmt=con.createStatement();
                }
                String sql2="SELECT Correct2 FROM ques WHERE Course='"+(s)+"'";
               rs=stmt.executeQuery(sql2);
            String correct2="";
            while(rs.next()){
                correct2=rs.getString("Correct2");
                stmt=con.createStatement();
              String crb1=jRadioButton1.getText();
              String crb2=jRadioButton2.getText();
              String crb3=jRadioButton3.getText();
              String crb4=jRadioButton4.getText();
              if(jRadioButton1.isSelected() && crb1.equals(correct2)){
                  count++;
              }
              else
                  if(jRadioButton2.isSelected() && crb2.equals(correct2)){
                  count++;
            }
              else
                      if(jRadioButton3.isSelected() && crb3.equals(correct2)){
                  count++;
                
                      }
              else
                          if(jRadioButton4.isSelected() && crb4.equals(correct2)){
                  count++;
            }
              if(jRadioButton1.isSelected()||jRadioButton2.isSelected()||jRadioButton3.isSelected()||jRadioButton4.isSelected()){
           jButton5.setBackground(Color.RED);
                  
              }
                if(jRadioButton1.isSelected()){
                 b=1;
              }
              else
                  if(jRadioButton2.isSelected()){
                      b=2;
            }
              else
                      if(jRadioButton3.isSelected()){
                b=3;
                      }
              else
                          if(jRadioButton4.isSelected()){
                              b=4;
            }
            }
            }
            catch (SQLException e ) {
    e.printStackTrace();

}
         
        
         }
         catch(Exception e){
             e.printStackTrace();
         }
    }
     if(question==2){
         try{   
             String s = jTextField1.getText();
            try{
                String sql3="select Course  from ques where Course='"+(s)+"'";
                rs=stmt.executeQuery(sql3);
                String course="";
                while(rs.next()){
                    course=rs.getString("Course");

                    stmt=con.createStatement();
                }
                String sql2="SELECT Correct3 FROM ques WHERE Course='"+(s)+"'";
               rs=stmt.executeQuery(sql2);
            String correct3="";
            while(rs.next()){
                correct3=rs.getString("Correct3");
                stmt=con.createStatement();
              String crb1=jRadioButton1.getText();
              String crb2=jRadioButton2.getText();
              String crb3=jRadioButton3.getText();
              String crb4=jRadioButton4.getText();
        if(jRadioButton1.isSelected() && crb1.equals(correct3)){
              count++;
              }
              else
                  if(jRadioButton2.isSelected() && crb2.equals(correct3)){
                  count++;
            }
              else                      if(jRadioButton3.isSelected() && crb3.equals(correct3)){
                 count++;
                
                      }
              else
                          if(jRadioButton4.isSelected() && crb4.equals(correct3)){
                  count++;
            }
        
        
        
              if(jRadioButton1.isSelected()||jRadioButton2.isSelected()||jRadioButton3.isSelected()||jRadioButton4.isSelected()){
           jButton9.setBackground(Color.RED);
              }
           if(jRadioButton1.isSelected()){
                 c=1;
              }
              else
                  if(jRadioButton2.isSelected()){
                      c=2;
            }
              else
                      if(jRadioButton3.isSelected()){
                c=3;
                      }
              else
                          if(jRadioButton4.isSelected()){
                              c=4;
            }
              }
            System.out.println(c);
            }
            catch (SQLException e ) {
    e.printStackTrace();

}
         
        
         }
         catch(Exception e){
             e.printStackTrace();
         }
    }
          if(question==3){
                  try{   
             String s = jTextField1.getText();
            try{
                String sql3="select Course  from ques where Course='"+(s)+"'";
                rs=stmt.executeQuery(sql3);
                String course="";
                while(rs.next()){
                    course=rs.getString("Course");

                    stmt=con.createStatement();
                }
                String sql2="SELECT Correct4 FROM ques WHERE Course='"+(s)+"'";
               rs=stmt.executeQuery(sql2);
            String correct4="";
            while(rs.next()){
                correct4=rs.getString("Correct4");
                stmt=con.createStatement();
              String crb1=jRadioButton1.getText();
              String crb2=jRadioButton2.getText();
              String crb3=jRadioButton3.getText();
              String crb4=jRadioButton4.getText();
              if(jRadioButton1.isSelected() && crb1.equals(correct4)){
                  count++;
              }
              else
                  if(jRadioButton2.isSelected() && crb2.equals(correct4)){
                  count++;
            }
              else
                      if(jRadioButton3.isSelected() && crb3.equals(correct4)){
                  count++;
                
                      }
              else
                          if(jRadioButton4.isSelected() && crb4.equals(correct4)){
                  count++;
            }
              if(jRadioButton1.isSelected()||jRadioButton2.isSelected()||jRadioButton3.isSelected()||jRadioButton4.isSelected()){
           jButton10.setBackground(Color.RED);
                  
              }
              if(jRadioButton1.isSelected()){
                 d=1;
              }
              else
                  if(jRadioButton2.isSelected()){
                      d=2;
            }
              else
                      if(jRadioButton3.isSelected()){
                d=3;
                      }
              else
                          if(jRadioButton4.isSelected()){
                              d=4;
            }
            }
            }
            catch (SQLException e ) {
    e.printStackTrace();

}
         
        
         }
         catch(Exception e){
             e.printStackTrace();
         }
                 }
          if(question==4){
              try{   
             String s = jTextField1.getText();
            try{
                String sql3="select Course  from ques where Course='"+(s)+"'";
                rs=stmt.executeQuery(sql3);
                String course="";
                while(rs.next()){
                    course=rs.getString("Course");

                    stmt=con.createStatement();
                }
                String sql2="SELECT Correct5 FROM ques WHERE Course='"+(s)+"'";
               rs=stmt.executeQuery(sql2);
            String correct5="";
            while(rs.next()){
                correct5=rs.getString("Correct5");
                stmt=con.createStatement();
              String crb1=jRadioButton1.getText();
              String crb2=jRadioButton2.getText();
              String crb3=jRadioButton3.getText();
              String crb4=jRadioButton4.getText();
              if(jRadioButton1.isSelected() && crb1.equals(correct5)){
                  count++;
              }
              else
                  if(jRadioButton2.isSelected() && crb2.equals(correct5)){
                  count++;
            }
              else
                      if(jRadioButton3.isSelected() && crb3.equals(correct5)){
                  count++;
                
                      }
              else
                          if(jRadioButton4.isSelected() && crb4.equals(correct5)){
                  count++;
            }
              if(jRadioButton1.isSelected()||jRadioButton2.isSelected()||jRadioButton3.isSelected()||jRadioButton4.isSelected()){
           jButton11.setBackground(Color.RED);
                  
              }
              if(jRadioButton1.isSelected()){
                 e=1;
              }
              else
                  if(jRadioButton2.isSelected()){
                      e=2;
            }
              else
                      if(jRadioButton3.isSelected()){
                e=3;
                      }
              else
                          if(jRadioButton4.isSelected()){
                              e=4;
            }
            }
            }
            catch (SQLException e ) {
    e.printStackTrace();

}
         
        
         }
         catch(Exception e){
             e.printStackTrace();
         }
         }
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         
            
        setQues();
    
        
        
         
     
    
       
        
                
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
                                               
        Timer timer = new Timer(); //new timer
        counter = 300; //setting the counter to 10 sec
        TimerTask task = new TimerTask() {         
            public void run() {                
                jLabel1.setText(Integer.toString(counter)); //the timer lable to counter.
                counter --;
                if (counter == -1){
                    timer.cancel();
                    JOptionPane.showConfirmDialog(null, "Time's Up!");
                   check();
        
        jLabel15.setText(String.valueOf(count));
        double percent = ((double)count/5)*100;
        jLabel10.setText(String.valueOf(percent));
                } else if(isIt){
                    timer.cancel();
                    isIt = false;
                    dispose();
                    
                }
            }
        };
    timer.scheduleAtFixedRate(task, 1000, 1000); // =  timer.scheduleAtFixedRate(task, delay, period);
              
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        check();
        question++;
        setQues();
        jRadioButton1.setSelected(false);
                      jRadioButton2.setSelected(false);
                      
           jRadioButton3.setSelected(false);
                      jRadioButton4.setSelected(false);
        if(b==1 | b==2 | b==3 | b==4 && b1==1){
            this.bAns();
            b1=0;
            
            
        
        }
       
        
        
         if(c==1 | c==2 | c==3 | c==4 && b2==1){
            this.cAns();
            b2=0;
            
            
        }
        
         
         if(d==1 | d==2 | d==3 | d==4 && b3==1){
            this.dAns();
            b3=0;
            
            
        }
         if(e==1 | e==2 | e==3 | e==4 && b4==1){
            this.dAns();
            b4=0;
            
            
        }
        
         if(question==2){this.cAns();}
         
         if(question==3){this.dAns();}
         
         if(question==4){this.eAns();}
         
        
        
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
b1=1;
           jRadioButton1.setSelected(false);
                      jRadioButton2.setSelected(false);
                      
           jRadioButton3.setSelected(false);
                      jRadioButton4.setSelected(false);
        // TODO add your handling code here:
        check();
        question=0;
        setQues();
        if(a==1){
            jRadioButton1.setSelected(true);
        }
        else if(a==2){
            jRadioButton2.setSelected(true);
        }
        else if(a==3){
            jRadioButton3.setSelected(true);
        }
        else if(a==4){
            jRadioButton4.setSelected(true);
        }
        this.aAns();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        b2=0;
        jRadioButton1.setSelected(false);
                      jRadioButton2.setSelected(false);
                      
           jRadioButton3.setSelected(false);
                      jRadioButton4.setSelected(false);
        check();
        question=1;
        setQues();
         if(b==1){
            jRadioButton1.setSelected(true);
        }
        else if(b==2){
            jRadioButton2.setSelected(true);
        }
        else if(b==3){
            jRadioButton3.setSelected(true);
        }
        else if(b==4){
            jRadioButton4.setSelected(true);
        }
         b2++;
         this.bAns();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
       b3=0;
        jRadioButton1.setSelected(false);
                      jRadioButton2.setSelected(false);
                      
           jRadioButton3.setSelected(false);
                      jRadioButton4.setSelected(false);
        check();
        question=2;
        setQues();
         if(c==1){
            jRadioButton1.setSelected(true);
        }
        else if(c==2){
            jRadioButton2.setSelected(true);
        }
        else if(c==3){
            jRadioButton3.setSelected(true);
        }
        else if(c==4){
            jRadioButton4.setSelected(true);
        }
         
       b3++; 
this.cAns();        
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        b4=0;
        jRadioButton1.setSelected(false);
                      jRadioButton2.setSelected(false);
                      
           jRadioButton3.setSelected(false);
                      jRadioButton4.setSelected(false);
        check();
        question=3;
        setQues();
        if(d==1){
            jRadioButton1.setSelected(true);
        }
        else if(d==2){
            jRadioButton2.setSelected(true);
        }
        else if(d==3){
            jRadioButton3.setSelected(true);
        }
        else if(d==4){
            jRadioButton4.setSelected(true);
        }
        b4++;
        this.dAns();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        b5=0;
        jRadioButton1.setSelected(false);
                      jRadioButton2.setSelected(false);
                      
           jRadioButton3.setSelected(false);
                      jRadioButton4.setSelected(false);
        check();
        question=4;
        setQues();
        if(e==1){
            jRadioButton1.setSelected(true);
        }
        else if(e==2){
            jRadioButton2.setSelected(true);
        }
        else if(e==3){
            jRadioButton3.setSelected(true);
        }
        else if(e==4){
            jRadioButton4.setSelected(true);
        }
        
        b5++;
        this.eAns();
       
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        if(a==1 | a==2 | a==3 | a==4){
            l5++;
        }
        
        if(b==1 | b==2 | b==3 | b==4){
            l5++;
        }
        
         if(c==1 | c==2 | c==3 | c==4){
            l5++;
        }
        
        if(d==1 | d==2 | d==3 | d==4){
            l5++;
        }
        if(e==1 | e==2 | e==3 | e==4){
            l5++;
        }
        
        
        
       
        
        

        
        
        
        jLabel15.setText(String.valueOf(l5));
        double percent = ((double)l5/5)*100;
        jLabel10.setText(String.valueOf(percent));
         if(l5==5){
             JOptionPane.showMessageDialog(null,"Congratulations, Passed 100% ");
             
         }
        try{
            String sql="INSERT INTO result(name, course, correct, percentage) VALUES (?,?,?,?)";  
                    pst=con.prepareStatement(sql);
            pst.setString(1,jLabel7.getText());
            pst.setString(2,jTextField1.getText());
            pst.setString(3,jLabel15.getText());
             pst.setString(4,jLabel10.getText());
             int rowsInserted = pst.executeUpdate();
			if (rowsInserted > 0) {
                            System.out.println( "the result details have been registered in the database");
			}}
                        catch (Exception ex) {
			ex.printStackTrace();
                                }    
        
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainTest().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JRadioButton jRadioButton1;
    public javax.swing.JRadioButton jRadioButton2;
    public javax.swing.JRadioButton jRadioButton3;
    public javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    public javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    private void bAns() {
        
        if(b==1){
            jRadioButton1.setSelected(true);
        }
        else if(b==2){
            jRadioButton2.setSelected(true);
        }
        else if(b==3){
            jRadioButton3.setSelected(true);
        }
        else if(b==4){
            jRadioButton4.setSelected(true);
        }}
    public void aAns(){
        if(a==1){
            jRadioButton1.setSelected(true);
        }
        else if(a==2){
            jRadioButton2.setSelected(true);
        }
        else if(a==3){
            jRadioButton3.setSelected(true);
        }
        else if(a==4){
            jRadioButton4.setSelected(true);
        }
    }
    public void cAns(){
        if(c==1){
            jRadioButton1.setSelected(true);
        }
        else if(c==2){
            jRadioButton2.setSelected(true);
        }
        else if(c==3){
            jRadioButton3.setSelected(true);
        }
        else if(c==4){
            jRadioButton4.setSelected(true);
        }
    }
    public void dAns(){
        if(d==1){
            jRadioButton1.setSelected(true);
        }
        else if(d==2){
            jRadioButton2.setSelected(true);
        }
        else if(d==3){
            jRadioButton3.setSelected(true);
        }
        else if(d==4){
            jRadioButton4.setSelected(true);
        }
    }
     public void eAns(){
        if(e==1){
            jRadioButton1.setSelected(true);
        }
        else if(e==2){
            jRadioButton2.setSelected(true);
        }
        else if(e==3){
            jRadioButton3.setSelected(true);
        }
        else if(e==4){
            jRadioButton4.setSelected(true);
        }
    }
}
